name: waste_management_tracking
description: Waste Management Tracking System for Sri Lanka

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.0

  # Firebase for authentication and backend
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_app_check: ^0.3.1+7
  flutter_secure_storage: ^9.2.2
  firebase_remote_config: ^5.3.0

  # Package for app version info_popup

  package_info_plus: ^8.1.3

  # Google Maps Integration
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2

  # State Management
  provider: ^6.1.2

  # GPS and Location Services
  geolocator: ^9.0.2

  # Networking
  http: ^1.2.2

  # Additional UI Packages
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.1
  image: ^4.5.2
  custom_info_window: ^1.0.1
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.12
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - map_theme/retro_theme.json
    - assets/images/
    - assets/route_maps/

flutter_native_splash:
  color: "#FFFFFF" # Background color (replace with green, e.g., "#00A65A")
  image: assets/images/logo.png # Path to your custom logo
  android: true
  ios: true
  web: false
  android_gravity: center # Center the logo for Android devices
  ios_content_mode: center # Center the logo for iOS devices

flutter_icons:
  android: true
  ios: true
  background_color: "#FFFFFF"
  image_path: "assets/images/logo.png"