// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWszsgHqTvgoYd_3INUbx98UHXlBCiMfI',
    appId: '1:292559066781:web:4e430aba2bf8bc050d2674',
    messagingSenderId: '292559066781',
    projectId: 'waste-management-project-fa040',
    authDomain: 'waste-management-project-fa040.firebaseapp.com',
    databaseURL: 'https://waste-management-project-fa040-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-project-fa040.firebasestorage.app',
    measurementId: 'G-L15YH85YBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsSHZjAU3ra4QIkE6a1mboeWRj7Kq6KM',
    appId: '1:292559066781:android:41183651be8228eb0d2674',
    messagingSenderId: '292559066781',
    projectId: 'waste-management-project-fa040',
    databaseURL: 'https://waste-management-project-fa040-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-project-fa040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnn8xGaK5hEipVw165W389G7iG1Aj2xEY',
    appId: '1:292559066781:ios:1308345171c84fe30d2674',
    messagingSenderId: '292559066781',
    projectId: 'waste-management-project-fa040',
    databaseURL: 'https://waste-management-project-fa040-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-project-fa040.firebasestorage.app',
    androidClientId: '292559066781-afu2u9uq294fv9gefmg9u78svjp1huv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnn8xGaK5hEipVw165W389G7iG1Aj2xEY',
    appId: '1:292559066781:ios:1308345171c84fe30d2674',
    messagingSenderId: '292559066781',
    projectId: 'waste-management-project-fa040',
    databaseURL: 'https://waste-management-project-fa040-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-project-fa040.firebasestorage.app',
    androidClientId: '292559066781-afu2u9uq294fv9gefmg9u78svjp1huv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWszsgHqTvgoYd_3INUbx98UHXlBCiMfI',
    appId: '1:292559066781:web:4e430aba2bf8bc050d2674',
    messagingSenderId: '292559066781',
    projectId: 'waste-management-project-fa040',
    authDomain: 'waste-management-project-fa040.firebaseapp.com',
    databaseURL: 'https://waste-management-project-fa040-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-project-fa040.firebasestorage.app',
    measurementId: 'G-L15YH85YBN',
  );

}